<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction-to-NumPy" data-toc-modified-id="Introduction-to-NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction to NumPy</a></span><ul class="toc-item"><li><span><a href="#What-is-NumPy?" data-toc-modified-id="What-is-NumPy?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is NumPy?</a></span></li><li><span><a href="#Keypoints" data-toc-modified-id="Keypoints-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Keypoints</a></span></li><li><span><a href="#NumPy-Array" data-toc-modified-id="NumPy-Array-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>NumPy Array</a></span></li><li><span><a href="#N-dimensional-Array" data-toc-modified-id="N-dimensional-Array-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>N-dimensional Array</a></span></li><li><span><a href="#Getting-Started" data-toc-modified-id="Getting-Started-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Getting Started</a></span></li><li><span><a href="#Why-Numpy?" data-toc-modified-id="Why-Numpy?-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Why Numpy?</a></span></li><li><span><a href="#Calculation" data-toc-modified-id="Calculation-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Calculation</a></span></li><li><span><a href="#Less-Memory" data-toc-modified-id="Less-Memory-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Less Memory</a></span></li><li><span><a href="#Faster" data-toc-modified-id="Faster-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Faster</a></span></li><li><span><a href="#Creating-Arrays" data-toc-modified-id="Creating-Arrays-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Creating Arrays</a></span></li><li><span><a href="#Array-with-Categorical-Entities" data-toc-modified-id="Array-with-Categorical-Entities-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Array with Categorical Entities</a></span></li><li><span><a href="#Inspecting-array-properties" data-toc-modified-id="Inspecting-array-properties-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Inspecting array properties</a></span><ul class="toc-item"><li><span><a href="#Size" data-toc-modified-id="Size-1.12.1"><span class="toc-item-num">1.12.1&nbsp;&nbsp;</span>Size</a></span></li><li><span><a href="#Shape" data-toc-modified-id="Shape-1.12.2"><span class="toc-item-num">1.12.2&nbsp;&nbsp;</span>Shape</a></span></li><li><span><a href="#Data-Type" data-toc-modified-id="Data-Type-1.12.3"><span class="toc-item-num">1.12.3&nbsp;&nbsp;</span>Data Type</a></span></li></ul></li><li><span><a href="#Type-Conversion" data-toc-modified-id="Type-Conversion-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Type Conversion</a></span></li><li><span><a href="#Numpy-array-to-Python-List" data-toc-modified-id="Numpy-array-to-Python-List-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>Numpy array to Python List</a></span></li><li><span><a href="#Get-Help:-View-documentation" data-toc-modified-id="Get-Help:-View-documentation-1.15"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>Get Help: View documentation</a></span></li><li><span><a href="#References" data-toc-modified-id="References-1.16"><span class="toc-item-num">1.16&nbsp;&nbsp;</span>References</a></span></li></ul></li></ul></div>

# Introduction to NumPy

## What is NumPy?

NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc. It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data. Now, let me tell you what exactly is a python numpy array.

## Keypoints 
- Numpy stands for numerical Python
- Fundamental package for numerical computations in Python
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

## NumPy Array
Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize numpy arrays from nested Python lists and access it elements. In order to perform these numpy operations.

## N-dimensional Array
- 1Dimensional(1D) Array
- 2Dimensional(2D) Array
- 3Dimensional(3D) Array
![NdArray](../img/arrays.png)

## Getting Started
Use the following import convention
```python
import numpy as np
```

## Why Numpy?
- Less Memory
- Fast
- Convenient

## Calculation
- Element wise sum is not possible in Python list. But numpy can do that it is an advantage of numpy array


In [21]:
# add 2 lists 
L1 = [1, 2, 3]
L2 = [4, 5, 6]
print(L1+L2)

[1, 2, 3, 4, 5, 6]


In [22]:
# element wise sum using numpy array 
import numpy as np 
A1 = np.array([1, 2, 3])
A2 = np.array([4, 5, 6])
print(A1+A2)

[5 7 9]


## Less Memory

In [1]:
import numpy as np
import time
import sys
S = range(1000)
print("Python List: ", sys.getsizeof(5)*len(S))
 
D = np.arange(1000)
print("Numpy Array: ", D.size*D.itemsize)

Python List:  28000
Numpy Array:  8000


## Faster

In [16]:
import time
import sys
 
SIZE = 1000000
 
L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
# time in ms 
print((time.time()-start)*1000)
 
start = time.time()
result = A1+A2
# time in ms 
print((time.time()-start)*1000)

196.61378860473633
56.15043640136719


In [17]:
%timeit sum(range(1000))

19.5 µs ± 354 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [18]:
%timeit np.sum(np.arange(1000))

8.63 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Creating Arrays 
- **Array:** Ordered collection of elements of basic data types of given length.
- **Syntax**
```python 
np.array(object)
```

In [2]:
# import numpy 
import numpy as np 

In [5]:
# Creating 1D array
A = np.array([1, 2, 3])
print(A)

[1 2 3]


In [7]:
# type 
print(type(A))

<class 'numpy.ndarray'>


## Array with Categorical Entities 
- Numpy can handle different categorical entities. 
- All elements are coerced into same data type 

In [13]:
# create an array with categorical entities. 
X = np.array([12, 13, "n"])
print(X)

['12' '13' 'n']


In [14]:
# type 
print(type(X))

<class 'numpy.ndarray'>


In [15]:
# Creating 2D array
A2 = np.array([[3, 4, 5], [7, 8, 9]])
print(A2) 

[[3 4 5]
 [7 8 9]]


In [16]:
# Creating 3D array
A3 = np.array([[(1, 2, 3), (4, 5, 6)], [(7, 8, 9), (10, 11, 12)]])
print(A3) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Inspecting array properties

### Size 
- Returns number of elements in array
- **Syntax:** `array.size`

In [3]:
A1 = np.array([1, 2, 3,4, 5])
# size 
A1.size

5

### Shape
- Returns dimensions of array (rows,columns)
- **Syntax:** `array.shape`

In [4]:
A2 = np.array([[4, 5, 6], [7, 8, 9]])
# shape 
A2.shape 

(2, 3)

In [11]:
# get row 
A2.shape[0]

2

In [12]:
# get column
A2.shape[1]

3

### Data Type
- Returns type of elements in array
- **Syntax:** `array.size`

In [6]:
A3 = np.linspace(0, 100, 6)
# dtypes 
A3.dtype

dtype('float64')

 ## Type Conversion 
 - Convert array elements to type dtype
 - **Syntax:** `array.astype(dtype)`
     - dtype - data type 

In [7]:
A4 = np.ones((2,3))
# convert 
A4.astype(np.float16)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

## Numpy array to Python List 
- Returns the Python list 
- **Syntax:** `array.tolist()`

In [8]:
A5 = np.linspace(0, 100, 20)
# array to list 
A5.tolist() 

[0.0,
 5.2631578947368425,
 10.526315789473685,
 15.789473684210527,
 21.05263157894737,
 26.315789473684212,
 31.578947368421055,
 36.8421052631579,
 42.10526315789474,
 47.36842105263158,
 52.631578947368425,
 57.89473684210527,
 63.15789473684211,
 68.42105263157896,
 73.6842105263158,
 78.94736842105263,
 84.21052631578948,
 89.47368421052633,
 94.73684210526316,
 100.0]

## Get Help: View documentation
- Returns a documentation
- **Syntax:** `np.info(np.function)`
    - function - linspace, logspace, eye, ones, zeros etc.

In [10]:
np.info(np.linspace)

 linspace(*args, **kwargs)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dty

## References
- https://numpy.org/
- https://www.edureka.co/blog/python-numpy-tutorial/
- https://github.com/enthought/Numpy-Tutorial-SciPyConf-2019
- [Python Machine Learning Cookbook](https://www.amazon.com/Python-Machine-Learning-Cookbook-Prateek/dp/1786464470)
<hr>

*This notebook was created by [Jubayer Hossain](https://jhossain.me/) | Copyright &copy; 2020, [Jubayer Hossain](https://jhossain.me/)*